// Generated by CoffeeScript 1.3.3
(function() {
  var requireFormFill;

  requireFormFill = function(e) {
    var canContinue, field, locationOfError, _i, _len, _ref, _ref1;
    canContinue = true;
    locationOfError = 0;
    _ref = $('input');
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      field = _ref[_i];
      if (!$(field).hasClass('optional-field') && !((_ref1 = $(field).val()) != null ? _ref1.length : void 0)) {
        $(field).addClass('error');
        if (canContinue) {
          locationOfError = $(field).prev()[0].offsetTop;
        }
        canContinue = false;
      } else {
        $(field).removeClass('error');
      }
    }
    if (!canContinue) {
      window.scrollTo(0, locationOfError);
      return e.preventDefault();
    }
  };

  $('#sign-up').click(requireFormFill);

  $('#log-in').click(requireFormFill);

}).call(this);
