// Generated by CoffeeScript 1.3.3
(function() {
  var readEmail, requireFormFill, saveEmail;

  saveEmail = function(email) {
    var expiryDate;
    expiryDate = new Date();
    expiryDate.setMinutes(expiryDate.getMinutes() + 20);
    return document.cookie = 'email=' + email + '; ' + 'expires=' + expiryDate.toGMTString() + '; path=/';
  };

  readEmail = function() {
    var cookie, name, value, _i, _len, _ref, _ref1;
    _ref = document.cookie.split(';');
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      cookie = _ref[_i];
      if (cookie != null) {
        _ref1 = cookie.split('='), name = _ref1[0], value = _ref1[1];
        if (name === 'email') {
          return value;
        }
      }
    }
    return null;
  };

  requireFormFill = function(e) {
    var canContinue, field, locationOfError, _i, _len, _ref, _ref1;
    canContinue = true;
    locationOfError = 0;
    _ref = $('input');
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      field = _ref[_i];
      if (!$(field).hasClass('optional-field') && !((_ref1 = $(field).val()) != null ? _ref1.length : void 0)) {
        $(field).addClass('error');
        $(field).prev().addClass('error');
        if (canContinue) {
          locationOfError = $(field).prev()[0].offsetTop;
        }
        canContinue = false;
      } else {
        $(field).prev().removeClass('error');
        $(field).removeClass('error');
      }
    }
    if (!canContinue) {
      window.scrollTo(0, locationOfError);
      e.preventDefault();
    }
    return canContinue;
  };

  $('#log-in-email-field').blur(function(e) {
    if ((!readEmail()) || !(readEmail() === $(this).val()) && $(this).val().length > 0) {
      return $('.new-account-helper').css('display', 'block');
    }
  });

  $('#log-in-email-field').keypress(function(e) {
    return setTimeout((function() {
      if (readEmail() === $('#log-in-email-field').val()) {
        return $('.new-account-helper').css('display', 'none');
      }
    }), 0);
  });

  $('#sign-up').click(function(e) {
    if (requireFormFill(e)) {
      saveEmail($('#new-email-field').val());
      console.log(readEmail());
      return alert(readEmail());
    }
  });

  $('#log-in').click(requireFormFill);

}).call(this);
